spring:
  application:
    name: jenkins_demo
  datasource:
    url: jdbc:mariadb://192.168.56.56:3306/jenkins_demo
    username: homestead
    password: secret
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
    schema: classpath:db/schemal.sql

  jpa:
    show-sql: true
    generate-ddl: true
    database: MySQL
    hibernate:
      ddl-auto: none

server:
  port: 8080

mybatis-plus:
  type-aliases-package: com.miaotaizi.jenkins_demo.entity
  config-location: classpath:mybatis/config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0